Remove assignment of SelectedDiff.Encoding and relevant relevant resources
Changes in FormCommit.resx introduced
in d8c8dce93a070851ef4cea2bb2f93a1c76e00404
can't be compiled by resgen2.
<data name="SelectedDiff.Encoding"> lead to
error: "Invalid ResX input."
There are several changes introduced in commit af1c97972 which
are not related to authors intention "Only enable reset...".
I don't think SelectedDiff.Encoding is needed.
But i also don't know why resgen2 fails.